name: Docker

on:
  push:
    branches: [main]
  pull:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
      
        run: |
          docker build -f dockerfile -t ${{ secrets.DOCKER_USERNAME }}/jenkins_gitaction:v1.10 .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/jenkins_gitaction:v1.10
